<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN-5CG11970KK" failures="2" tests="5" name="Default test" time="127.633" errors="0" timestamp="2024-04-17T17:14:09 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.036"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="19.918">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;2&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<2> but was:<1>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at ApolloStepDefinition.Callback.it_should_increase_the_count(Callback.java:126)
at ✽.it should increase the count(file:///C:/Users/SAKRAVIN/Desktop/Apollo_About/resources/Features/Callback.feature:26)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="12.198"/>
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="37.001">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at ApolloStepDefinition.Callback.it_should_redirect_to_the_book_function(Callback.java:201)
at ✽.it should redirect to the book function(file:///C:/Users/SAKRAVIN/Desktop/Apollo_About/resources/Features/Callback.feature:46)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="44.001"/>
</testsuite> <!-- Default test -->
